title: ModVerse
description: Koleksi Aplikasi & Game Mod Terupdate
baseurl: ""
url: "https://destaseo.github.io"

# Theme & Setting
theme: minima
plugins:
  - jekyll-feed

# Tambahan untuk modding style
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
